package tk.quanjia.community.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
<<<<<<< HEAD
import org.apache.ibatis.session.RowBounds;
=======
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
import tk.quanjia.community.model.User;
import tk.quanjia.community.model.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_USER
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 05 13:03:49 CST 2022
=======
     * @mbg.generated Mon Jul 04 18:34:29 CST 2022
>>>>>>> 4b5e4bf1c167e09c38ce9bb2076a6f6e735b8b22
     */
    int updateByPrimaryKey(User row);
}